[package]
name = "prototty-renderer"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
tetris = { path = ".." }
prototty = { git = "https://github.com/stevebob/prototty", rev = "wasm-backend" }
prototty_elements = { git = "https://github.com/stevebob/prototty", rev = "wasm-backend" }
ansi_colour = "0.2"
cgmath = { git = "https://github.com/stevebob/cgmath", rev = "rand-0.4" }
