[package]
name = "glutin_app"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty_app = { path = "../prototty_app" }
prototty = "0.8"
prototty_glutin = "0.8"
rand = "0.4"
