[package]
name = "tetris"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
rand = "0.4"
cgmath = { git = "https://github.com/stevebob/cgmath", rev = "rand-0.4" }
