[package]
name = "wasm_app"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
tetris = { path = ".." }
prototty_app = { path = "../prototty_app" }
prototty = "0.10"
prototty_wasm ="0.10"
rand = "0.4"
