[package]
name = "wasm_app"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
tetris = { path = ".." }
prototty = { git = "https://github.com/stevebob/prototty", rev = "wasm-backend" }
prototty_wasm = { git = "https://github.com/stevebob/prototty", rev = "wasm-backend" }
prototty_app = { path = "../prototty_app" }
rand = "0.4"
