[package]
name = "wasm_app"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
tetris = { path = ".." }
prototty = "0.6"
prototty_wasm = "0.6"
prototty_app = { path = "../prototty_app" }
rand = "0.4"
