[package]
name = "web-app"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
tetris = { path = ".." }
prototty = { git = "https://github.com/stevebob/prototty", rev = "wasm-backend" }
prototty-renderer = { path = "../prototty-renderer" }
rand = "0.4"
