[package]
name = "tetris_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
tetris = { path = "../tetris" }
tetris_prototty = { path = "../prototty" }
prototty = "0.11"
prototty_wasm ="0.11"
rand = "0.4"
