[package]
name = "tetris_prototty"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
tetris = { path = "../tetris" }
prototty = "0.11"
prototty_common = "0.11"
rand = "0.4"
