[package]
name = "unix_app"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty = { git = "https://github.com/stevebob/prototty" }
prototty_unix = { git = "https://github.com/stevebob/prototty" }
prototty_app = { path = "../prototty_app" }
rand = "0.4"
