[package]
name = "unix_app"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty = "0.7"
prototty_unix = "0.7"
prototty_app = { path = "../prototty_app" }
rand = "0.4"
