[package]
name = "tetris_glutin"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
tetris_prototty = { path = "../prototty" }
prototty = "0.11"
prototty_glutin = "0.11"
rand = "0.4"
